export const PURCHASE_REQUEST_STATUS = {
  BEFORE_REQUEST: "요청전",
  REQUESTED: "요청됨",
  APPROVED: "승인완료",
  HOLD: "보류",
  REJECTED: "반려",
  CANCELLED: "취소",
} as const;

export type PurchaseRequestStatus =
  (typeof PURCHASE_REQUEST_STATUS)[keyof typeof PURCHASE_REQUEST_STATUS];

export const PURCHASE_REQUEST_STATUS_OPTIONS = [
  PURCHASE_REQUEST_STATUS.BEFORE_REQUEST,
  PURCHASE_REQUEST_STATUS.REQUESTED,
  PURCHASE_REQUEST_STATUS.APPROVED,
  PURCHASE_REQUEST_STATUS.HOLD,
  PURCHASE_REQUEST_STATUS.REJECTED,
  PURCHASE_REQUEST_STATUS.CANCELLED,
] as const;

export const PURCHASE_ORDER_STATUS = {
  BEFORE_ORDER: "발주전",
  PRE_PURCHASE: "선구매",
  ORDERED: "발주완료",
  SHIPPING: "배송중",
  HOLD: "보류",
  RECEIVED: "입고완료",
  CANCELLED: "취소",
} as const;

export type PurchaseOrderStatus =
  (typeof PURCHASE_ORDER_STATUS)[keyof typeof PURCHASE_ORDER_STATUS];

export const PURCHASE_ORDER_STATUS_OPTIONS = [
  PURCHASE_ORDER_STATUS.BEFORE_ORDER,
  PURCHASE_ORDER_STATUS.PRE_PURCHASE,
  PURCHASE_ORDER_STATUS.ORDERED,
  PURCHASE_ORDER_STATUS.SHIPPING,
  PURCHASE_ORDER_STATUS.HOLD,
  PURCHASE_ORDER_STATUS.RECEIVED,
  PURCHASE_ORDER_STATUS.CANCELLED,
] as const;

export const PURCHASE_RECEIVING_REVIEW_STATUS = {
  PENDING: "검토대기",
  COMPLETED: "검토완료",
} as const;

export type PurchaseReceivingReviewStatus =
  (typeof PURCHASE_RECEIVING_REVIEW_STATUS)[keyof typeof PURCHASE_RECEIVING_REVIEW_STATUS];

export const PURCHASE_RECEIVING_REVIEW_FILTER = {
  PENDING: "pending",
  COMPLETED: "completed",
} as const;

export type PurchaseReceivingReviewFilter =
  (typeof PURCHASE_RECEIVING_REVIEW_FILTER)[keyof typeof PURCHASE_RECEIVING_REVIEW_FILTER];
